version: '3'

services:
  blog_nginx:
    image: nginx:1.23.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${PORT80}:80"
      - "127.0.0.1:${PORT443}:443"
    volumes:
      - ./nginx-config/config:/etc/nginx/conf.d
      - certbot-config:/var/www/certbot
    extra_hosts:
      - "host.docker.internal:host-gateway"

  blog_certbot:
    image: certbot/certbot:v1.30.0
    restart: always
    env_file:
      - .env
    volumes:
      - ./scripts:/scripts
      - ${CERTBOT_CERT_PATH}:/etc/letsencrypt
      - certbot-config:/var/www/certbot
    entrypoint: "/bin/sh -c 'sh /scripts/start_certbot.sh'"

volumes:
  certbot-config:
