version: '3'

services:
  blog_certbot:
    image: certbot/certbot:v1.30.0
    restart: always
    env_file:
      - .env
    volumes:
      - ./scripts:/scripts
      - ${CERTBOT_CERT_PATH}:/etc/letsencrypt
      - ${CERTBOT_CERT_PATH}:/var/www/certbot
    entrypoint: "/bin/sh -c 'sh /scripts/start_certbot.sh'"
