name: Deployment prod nginx

on: [ push, pull_request ]

jobs:

  # Deploy frontend
  deploy-prod-nginx:

    if: github.ref == 'refs/heads/guilledev'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create env variables file
        run: |
          echo 'DOMAINS="${{ secrets.ANGEMY_PROD_DOMAINS }}"' > .env
          echo "DOMAIN=${{ secrets.ANGEMY_PROD_DOMAIN }}" >> .env
          echo "EMAIL=contact@guilledev.com" >> .env
          echo "CERTBOT_CERT_PATH=${{ secrets.ANGEMY_PROD_CERTBOT_CERT_PATH }}" >> .env
          echo "CERTBOT_CONF_PATH=${{ secrets.ANGEMY_PROD_CERTBOT_CONF_PATH }}" >> .env

      - name: Copy project to the hosting
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.PROD_ANGEMY__REMOTE_TARGET }}

      - name: Deploy project with docker in hosting
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.PROD_ANGEMY__REMOTE_TARGET }} && ./deploy.sh prod_angemy
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SERVER_SSH_KEY}}
